
$lines = Get-Content -Path "C:\Users\ASUS\OneDrive\Documents\GitHub\reposcore\app.py"
$start = $lines.IndexOf("    with st.spinner(`"Fetching repo data from GitHub API...`":)")
$end = $lines.IndexOf("            # Confidence report - explicit match rate and exceptions count")
if ($start -ge 0 -and $end -ge 0) {
    $newblock = @(
        "    with st.spinner(`"Fetching repo data from GitHub API...`":)",
        "        try:",
        "            features = fetch_repo_features(repo_input, headers=headers)",
        "        except RepoFetchError as e:",
        "            # Log the failure to audit trail",
        "            minimal_features = {",
        "                `"full_name`": repo_input,",
        "                `"html_url`": f`"https://github.com/{repo_input}`"",,
        "                `"stars`": 0,",
        "                `"forks`": 0,",
        "                `"open_issues`": 0,",
        "                `"readme_size`": 0,",
        "                `"repo_age_days`": 0,",
        "                `"last_commit_days`": 0,",
        "                `"has_readme`": 0,",
        "                `"topics`": [],",
        "            }",
        "            log_audit_trail(minimal_features, 0.0, 0, 0.3, caveats=[f`"GitHub fetch failed: {str(e)}`"])",
        "            st.error(str(e))",
        "        else:",
        "            topics = features[`"topics`"]",
        "            repo_age_days = features[`"repo_age_days`"]",
        "",
        "            X_dense = featurize(features, tfidf_readme, tfidf_topics, scaler)",
        "",
        "            # Generate Predictions -- use the user-chosen threshold, not the",
        "            # model`s built-in 0.5 cutoff (see slider help text / README for why)",
        "            probability = rf_model.predict_proba(X_dense)[0][1]",
        "            prediction = 1 if probability >= threshold else 0",
        "",
        "            # Check for exceptions and low confidence",
        "            exceptions = check_exceptions(features)",
        "            low_confidence = 0.4 <= probability <= 0.6  # Model uncertainty band",
        "            warning_messages = exceptions.copy()",
        "            if low_confidence:",
        "                warning_messages.append(`"Low confidence prediction (probability near 0.5).`")",
        "",
        "            # AI review (if available) and add its status to caveats",
        "            ai_result = None",
        "            if AI_REVIEW_AVAILABLE:",
        "                try:",
        "                    # Cached AI review to avoid repeated API calls for same repo",
        "                    @st.cache_data(ttl=86400, show_spinner=False)",
        "                    def _cached_ai_review(readme_text_clean: str, features_hashable: tuple, prediction: int, probability: float):",
        "                        # Rebuild features dict from hashable tuple",
        "                        features_dict = dict(features_hashable)",
        "                        return generate_ai_review(",
        "                            readme_content=readme_text_clean,",
        "                            features=features_dict,",
        "                            prediction=prediction,",
        "                            probability=probability",
        "                        )",
        "",
        "                    readme_text = features.get(`"readme_text_clean`", `"`)",
        "                    # We need to create a hashable tuple of the features, converting lists to tuples.",
        "                    hashable_features = []",
        "                    for k, v in sorted(features.items()):",
        "                        if isinstance(v, list):",
        "                            hashable_features.append((k, tuple(v)))",
        "                        else:",
        "                            hashable_features.append((k, v))",
        "                    features_hashable = tuple(hashable_features)",
        "",
        "                    ai_result = _cached_ai_review(readme_text, features_hashable, prediction, probability)",
        "                    # Append AI review status to warning_messages",
        "                    status = ai_result.get(`"status`", `"unknown`")",
        "                    if status == `"success`":",
        "                        warning_messages.append(`"AI review: success`")",
        "                    elif status == `"skipped`":",
        "                        warning_messages.append(f`"AI review: skipped ({ai_result.get(`"review`", `"unknown reason`")}`")",
        "                    else:  # error",
        "                        warning_messages.append(f`"AI review: error ({ai_result.get(`"review`", `"unknown error`")})`")",
        "                except Exception as err:",
        "                    warning_messages.append(f`"AI review: error ({str(err)})`")",
        "",
        "            # Log to audit trail",
        "            log_audit_trail(features, probability, prediction, threshold, caveats=warning_messages)"
    )
    # Replace lines
    $lines = $lines[0..($start-1)] + $newblock + $lines[$end..($lines.Length-1)]
    Set-Content -Path "C:\Users\ASUS\OneDrive\Documents\GitHub\reposcore\app.py" -Value ($lines -join "`r`n") -Encoding UTF8
    Write-Host "Replacement done"
} else {
    Write-Host "Start or end not found: start=$start, end=$end"
}

