f = open('C:/Users/ASUS/OneDrive/Documents/GitHub/reposcore/tests/test_model_and_api.py', 'a', encoding='utf-8')
f.write('\n\n')
f.write('\nclass TestModelPrediction:')
f.write('\n    """Test that model predictions work and return valid ranges."""')
f.write('\n')
f.write('\n    @pytest.fixture')
f.write('\n    def models(self):')
f.write('\n        """Load all model artifacts."""')
f.write('\n        return (')
f.write('\n            joblib.load(os.path.join(MODELS_DIR, "rf_model.pkl")),')
f.write('\n            joblib.load(os.path.join(MODELS_DIR, "tfidf_readme.pkl")),')
f.write('\n            joblib.load(os.path.join(MODELS_DIR, "tfidf_topics.pkl")),')
f.write('\n            joblib.load(os.path.join(MODELS_DIR, "scaler.pkl")),')
f.write('\n        )')
f.write('\n')
f.write('\n    def test_predict_proba_returns_valid_probability(self, models):')
f.write('\n        """predict_proba returns a probability in [0, 1]."""')
f.write('\n        rf_model, tfidf_readme, tfidf_topics, scaler = models')
f.write('\n        ')
f.write('\n        from reposcore_utils import featurize')
f.write('\n        ')
f.write('\n        features = {')
f.write('\n            "full_name": "test/repo",')
f.write('\n            "html_url": "https://github.com/test/repo",')
f.write('\n            "topics": ["python", "ml"],')
f.write('\n            "stars": 100,')
f.write('\n            "forks": 10,')
f.write('\n            "open_issues": 5,')
f.write('\n            "repo_age_days": 365,')
f.write('\n            "last_commit_days": 7,')
f.write('\n            "total_contributors": 5,')
f.write('\n            "has_tests": True,')
f.write('\n            "has_ci": True,')
f.write('\n            "has_license": True,')
f.write('\n            "readme_size": 5000,')
f.write('\n            "readme_text_clean": "This is a test readme with documentation.",')
f.write('\n            "commit_count_90d": 20,')
f.write('\n            "issue_response_hours": 24,')
f.write('\n            "pr_merge_time_days": 3,')
f.write('\n            "contributor_commits_last_90d": 50,')
f.write('\n            "is_archived": False,')
f.write('\n            "is_fork": False,')
f.write('\n            "stars_per_month": 2.5,')
f.write('\n            "has_readme": 1,')
f.write('\n        }')
f.write('\n        ')
f.write('\n        X = featurize(features, tfidf_readme, tfidf_topics, scaler)')
f.write('\n        proba = rf_model.predict_proba(X)[0][1]')
f.write('\n        ')
f.write('\n        assert proba is not None')
f.write('\n        assert 0.0 <= proba <= 1.0')
f.write('\n        assert isinstance(proba, (float, np.floating))')
f.write('\n')
f.write('\n    def test_predict_returns_valid_class(self, models):')
f.write('\n        """predict returns a valid class (0 or 1)."""')
f.write('\n        rf_model, tfidf_readme, tfidf_topics, scaler = models')
f.write('\n        ')
f.write('\n        from reposcore_utils import featurize')
f.write('\n        ')
f.write('\n        features = {')
f.write('\n            "full_name": "test/repo",')
f.write('\n            "html_url": "https://github.com/test/repo",')
f.write('\n            "topics": ["python", "ml"],')
f.write('\n            "stars": 100,')
f.write('\n            "forks": 10,')
f.write('\n            "open_issues": 5,')
f.write('\n            "repo_age_days": 365,')
f.write('\n            "last_commit_days": 7,')
f.write('\n            "total_contributors": 5,')
f.write('\n            "has_tests": True,')
f.write('\n            "has_ci": True,')
f.write('\n            "has_license": True,')
f.write('\n            "readme_size": 5000,')
f.write('\n            "readme_text_clean": "This is a test readme with documentation.",')
f.write('\n            "commit_count_90d": 20,')
f.write('\n            "issue_response_hours": 24,')
f.write('\n            "pr_merge_time_days": 3,')
f.write('\n            "contributor_commits_last_90d": 50,')
f.write('\n            "is_archived": False,')
f.write('\n            "is_fork": False,')
f.write('\n            "stars_per_month": 2.5,')
f.write('\n            "has_readme": 1,')
f.write('\n        }')
f.write('\n        ')
f.write('\n        X = featurize(features, tfidf_readme, tfidf_topics, scaler)')
f.write('\n        prediction = rf_model.predict(X)[0]')
f.write('\n        ')
f.write('\n        assert prediction in (0, 1)')
f.close()
print('Part 2 done')