f = open('C:/Users/ASUS/OneDrive/Documents/GitHub/reposcore/tests/test_model_and_api.py', 'a', encoding='utf-8')
f.write('\n\n')
f.write('\nclass TestFastAPIEndpoints:')
f.write('\n    """Test FastAPI endpoints using TestClient."""')
f.write('\n')
f.write('\n    @pytest.fixture')
f.write('\n    def client(self):')
f.write('\n        """Create TestClient for FastAPI app."""')
f.write('\n        from fastapi.testclient import TestClient')
f.write('\n        from api_server import app')
f.write('\n        return TestClient(app)')
f.write('\n')
f.write('\n    def test_health_endpoint(self, client):')
f.write('\n        """GET /api/health returns 200 with expected shape."""')
f.write('\n        response = client.get("/api/health")')
f.write('\n        ')
f.write('\n        assert response.status_code == 200')
f.write('\n        data = response.json()')
f.write('\n        assert data["status"] == "healthy"')
f.write('\n        assert "timestamp" in data')
f.write('\n        assert isinstance(data["timestamp"], str)')
f.write('\n')
f.write('\n    def test_submit_job_returns_job_id(self, client):')
f.write('\n        """POST /api/jobs returns 200 with job_id."""')
f.write('\n        response = client.post("/api/jobs?owner=testowner&repo=testrepo&threshold=0.3")')
f.write('\n        ')
f.write('\n        assert response.status_code == 200')
f.write('\n        data = response.json()')
f.write('\n        assert "job_id" in data')
f.write('\n        assert isinstance(data["job_id"], str)')
f.write('\n        assert len(data["job_id"]) > 0')
f.write('\n        assert data["status"] == "completed"')
f.write('\n        assert "result_key" in data')
f.write('\n')
f.write('\n    def test_get_repo_score_endpoint(self, client):')
f.write('\n        """GET /api/score/{owner}/{repo} returns 200 with score data."""')
f.write('\n        response = client.get("/api/score/testowner/testrepo")')
f.write('\n        ')
f.write('\n        assert response.status_code == 200')
f.write('\n        data = response.json()')
f.write('\n        assert "total_score" in data')
f.write('\n        assert "components" in data')
f.write('\n        assert "tier" in data')
f.write('\n        assert "probability" in data')
f.write('\n        assert "prediction" in data')
f.write('\n')
f.write('\n    def test_get_job_status_endpoint(self, client):')
f.write('\n        """GET /api/jobs/{job_id} returns 404 for non-existent job."""')
f.write('\n        response = client.get("/api/jobs/nonexistent-job-id")')
f.write('\n        ')
f.write('\n        assert response.status_code == 404')
f.write('\n')
f.write('\n    def test_badge_endpoint(self, client):')
f.write('\n        """GET /api/badge/{owner}/{repo} returns SVG."""')
f.write('\n        response = client.get("/api/badge/testowner/testrepo")')
f.write('\n        ')
f.write('\n        assert response.status_code == 200')
f.write('\n        assert response.headers["content-type"] == "image/svg+xml"')
f.write('\n        assert "svg" in response.text.lower()')
f.write('\n')
f.write('\n    def test_shields_badge_endpoint(self, client):')
f.write('\n        """GET /api/badges/{owner}/{repo} returns badge URL."""')
f.write('\n        response = client.get("/api/badges/testowner/testrepo")')
f.write('\n        ')
f.write('\n        assert response.status_code == 200')
f.write('\n        data = response.json()')
f.write('\n        assert "badge_url" in data')
f.write('\n        assert "shields.io" in data["badge_url"]')
f.write('\n')
f.write('\n')
f.write('\nif __name__ == "__main__":')
f.write('\n    pytest.main([__file__, "-v"])')
f.close()
print('Part 3 done')