f = open('C:/Users/ASUS/OneDrive/Documents/GitHub/reposcore/tests/test_model_and_api.py', 'w', encoding='utf-8')
f.write('"""')
f.write('\nTests for model loading, prediction, and FastAPI endpoints.')
f.write('\n\nThese tests verify:')
f.write('\n1. The ML model loads correctly from its saved file')
f.write('\n2. A single prediction call returns a valid score/confidence in expected range')
f.write('\n3. FastAPI endpoints return expected status codes and response shapes')
f.write('\n"""')
f.write('\nimport os')
f.write('\nimport sys')
f.write('\nimport pytest')
f.write('\nimport joblib')
f.write('\nimport numpy as np')
f.write('\nfrom unittest.mock import patch, MagicMock')
f.write('\n')
f.write('\nsys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))')
f.write('\n')
f.write('\nBASE_DIR = os.path.dirname(os.path.abspath(__file__))')
f.write('\nMODELS_DIR = os.path.join(BASE_DIR, "..", "models")')
f.write('\n')
f.write('\n')
f.write('\nclass TestModelLoading:')
f.write('\n    """Test that ML model artifacts load correctly."""')
f.write('\n')
f.write('\n    def test_rf_model_loads(self):')
f.write('\n        """RandomForest model loads without error."""')
f.write('\n        model_path = os.path.join(MODELS_DIR, "rf_model.pkl")')
f.write('\n        assert os.path.exists(model_path), f"Model file not found: {model_path}"')
f.write('\n        ')
f.write('\n        model = joblib.load(model_path)')
f.write('\n        assert model is not None')
f.write('\n        assert hasattr(model, "predict_proba")')
f.write('\n        assert hasattr(model, "predict")')
f.write('\n')
f.write('\n    def test_tfidf_readme_loads(self):')
f.write('\n        """TF-IDF vectorizer for README loads without error."""')
f.write('\n        path = os.path.join(MODELS_DIR, "tfidf_readme.pkl")')
f.write('\n        assert os.path.exists(path)')
f.write('\n        ')
f.write('\n        vectorizer = joblib.load(path)')
f.write('\n        assert vectorizer is not None')
f.write('\n        assert hasattr(vectorizer, "transform")')
f.write('\n')
f.write('\n    def test_tfidf_topics_loads(self):')
f.write('\n        """TF-IDF vectorizer for topics loads without error."""')
f.write('\n        path = os.path.join(MODELS_DIR, "tfidf_topics.pkl")')
f.write('\n        assert os.path.exists(path)')
f.write('\n        ')
f.write('\n        vectorizer = joblib.load(path)')
f.write('\n        assert vectorizer is not None')
f.write('\n        assert hasattr(vectorizer, "transform")')
f.write('\n')
f.write('\n    def test_scaler_loads(self):')
f.write('\n        """StandardScaler loads without error."""')
f.write('\n        path = os.path.join(MODELS_DIR, "scaler.pkl")')
f.write('\n        assert os.path.exists(path)')
f.write('\n        ')
f.write('\n        scaler = joblib.load(path)')
f.write('\n        assert scaler is not None')
f.write('\n        assert hasattr(scaler, "transform")')
f.close()
print('Part 1 done')